services:
  music-bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: ghcr.io/viet-aus-it/music-bot:production
    restart: unless-stopped
    env_file: './.env'
    volumes:
      - ./music/config.txt:/src/config.txt
      - ./music/serversettings.json:/src/serversettings.json
      - ./music/Playlists:/src/Playlists
