name: Build and Deploy Docker Images

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build-step:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/viet-aus-it/music-bot
          flavor: |
            latest=false
          tags: |
            type=sha
            type=raw,value=production

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}

  deploy-to-cloud-server:
    name: Deploy to Cloud Server
    runs-on: ubuntu-latest
    needs: build-step

    steps:
      - name: SSH into Cloud Server and deploy
        uses: appleboy/ssh-action@master
        env:
          SSH_USER: ${{ secrets.SSH_USER_EC2_CHATBOT }}
          REPO: ${{ github.event.repository.name }}
        with:
          envs: SSH_USER, REPO
          host: ${{ secrets.SSH_HOST_EC2_CHATBOT }}
          username: ${{ secrets.SSH_USER_EC2_CHATBOT }}
          key: ${{ secrets.SSH_KEY_EC2_CHATBOT }}
          script: |
            /usr/local/bin/deploy-musicbot \
              ${SSH_USER} \
              ${REPO} \
              /${REPO}/.env,.env