name: Build and Deploy Docker Images

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build-step:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/viet-aus-it/music-bot
          flavor: |
            latest=false
          tags: |
            type=sha
            type=raw,value=production

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
